# Generated by Django 2.2.19 on 2021-12-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211218_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='groups',
        ),
    ]
